### ISSUE TITLE
Add NuGet Package Manager Support

### ISSUE THREAD

**Issue by jaredbroad** [quantumtunneling/T-Digest.NET#1]
I'd love to import TDigest into QuantConnect for use by the community but we need package manager support to handle automatically updating. Would you please consider adding the project to NuGet?

Thanks!
Jared

PS: First Issue! :)

**Comment by quantumtunneling** [comment]
Hey Jared,

It's already on Nuget! Just do a search for TDigest. It was the only result last time I checked.

**Comment by quantumtunneling** [comment]
I should definitely mention that its on Nuget in the readme, so I'll do that

**Comment by jaredbroad** [comment]
Thanks @quantumtunneling, I searched for the T-Digest
